version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: zxstudio
      MYSQL_PASSWORD: zxstudio2023
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
